name: tp-python-06-11-25
services:

  react:
    build: ./front_employee
    container_name: front_app
    depends_on:
      - db-mysql
    ports:
      - 8087:3000
    networks:
      - back

  db-postgre:
    image: postgres
    container_name: db-postgre
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: tata
    restart: always
    volumes:
      - local_pgdata:/var/lib/postgresql
    ports:
      - 8001:5432
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    depends_on:
      - db-postgre
    environment:
      PMA_HOST: db-postgre
      PGADMIN_DEFAULT_EMAIL: a@a.fr
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 8002:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db_network

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  db_network: